openapi: 3.2.0
info:
  version: V1
  title: Orion Connect Fuse/Partner Apps API
  x-swagger-net-version: 8.4.12.001
servers:
- url: https://api.orionadvisor.com/api
tags:
- name: Fuse/PartnerApps
paths:
  /v1/Fuse/PartnerApps/{partnerAppId}/SmallImage:
    get:
      tags:
      - Fuse/PartnerApps
      operationId: FusePublicNotification_GetPartnerAppSmallImage
      parameters:
      - name: partnerAppId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: object
            application/json:
              schema:
                type: object
            text/json:
              schema:
                type: object
            multipart/form-data:
              schema:
                type: object
      security:
      - Authorization: []
      summary: Fuse public notification get partner app small image
      x-summary-source: derived
components:
  securitySchemes:
    Authorization:
      type: apiKey
      description: 'JWT Authorization header using the Session scheme. Example: "Authorization: Session {token}"'
      name: Authorization
      in: header
