openapi: 3.2.0
info:
  version: V1
  title: Orion Connect Utility/Html API
  x-swagger-net-version: 8.4.12.001
servers:
- url: https://api.orionadvisor.com/api
tags:
- name: Utility/Html
paths:
  /v1/Utility/Html/{sessionId}:
    get:
      tags:
      - Utility/Html
      operationId: Utility_HtmlAsync
      parameters:
      - name: sessionId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: cancellationToken
        in: header
        required: true
      - name: forceStepFunction
        in: query
        required: false
        schema:
          type: boolean
          default: false
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: object
            application/json:
              schema:
                type: object
            text/json:
              schema:
                type: object
            multipart/form-data:
              schema:
                type: object
      security:
      - Authorization: []
      summary: Utility html async
      x-summary-source: derived
components:
  securitySchemes:
    Authorization:
      type: apiKey
      description: 'JWT Authorization header using the Session scheme. Example: "Authorization: Session {token}"'
      name: Authorization
      in: header
