openapi: 3.2.0
info:
  version: V1
  title: Orion Connect Billing/Enums API
  x-swagger-net-version: 8.4.12.001
servers:
- url: https://api.orionadvisor.com/api
tags:
- name: Billing/Enums
paths:
  /v1/Billing/Enums:
    get:
      tags:
      - Billing/Enums
      operationId: Billing_GetEnums
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: object
            application/json:
              schema:
                type: object
            text/json:
              schema:
                type: object
            application/xml:
              schema:
                type: object
            text/xml:
              schema:
                type: object
            multipart/form-data:
              schema:
                type: object
      security:
      - Authorization: []
      summary: Billing get enums
      x-summary-source: derived
components:
  securitySchemes:
    Authorization:
      type: apiKey
      description: 'JWT Authorization header using the Session scheme. Example: "Authorization: Session {token}"'
      name: Authorization
      in: header
