openapi: 3.2.0
info:
  version: V1
  title: Orion Connect Integrations/Mind Touch Cls API
  x-swagger-net-version: 8.4.12.001
servers:
- url: https://api.orionadvisor.com/api
tags:
- name: Integrations/MindTouchCls
paths:
  /v1/Integrations/MindTouchCls/Redirect:
    get:
      tags:
      - Integrations/MindTouchCls
      operationId: MindTouch_Redirect
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: object
            application/json:
              schema:
                type: object
            text/json:
              schema:
                type: object
            multipart/form-data:
              schema:
                type: object
      security:
      - Authorization: []
      summary: Mind touch redirect
      x-summary-source: derived
components:
  securitySchemes:
    Authorization:
      type: apiKey
      description: 'JWT Authorization header using the Session scheme. Example: "Authorization: Session {token}"'
      name: Authorization
      in: header
