openapi: 3.2.0
info:
  version: V1
  title: Orion Connect Integrations/Marketor API
  x-swagger-net-version: 8.4.12.001
servers:
- url: https://api.orionadvisor.com/api
tags:
- name: Integrations/Marketor
paths:
  /v1/Integrations/Marketor/SSO:
    get:
      tags:
      - Integrations/Marketor
      operationId: Marketor_Get_SSO_UrlAsync
      parameters:
      - name: ct
        in: header
        required: true
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: object
            application/json:
              schema:
                type: object
            text/json:
              schema:
                type: object
            multipart/form-data:
              schema:
                type: object
      security:
      - Authorization: []
      summary: Marketor get SSO url async
      x-summary-source: derived
components:
  securitySchemes:
    Authorization:
      type: apiKey
      description: 'JWT Authorization header using the Session scheme. Example: "Authorization: Session {token}"'
      name: Authorization
      in: header
