openapi: 3.2.0
info:
  version: V1
  title: Orion Connect Rollups/Invalidate Todays Stored Performance…
  x-swagger-net-version: 8.4.12.001
servers:
- url: https://api.orionadvisor.com/api
tags:
- name: Rollups/InvalidateTodaysStoredPerformanceCheck
paths:
  /v1/Rollups/InvalidateTodaysStoredPerformanceCheck:
    post:
      tags:
      - Rollups/InvalidateTodaysStoredPerformanceCheck
      operationId: Rollups_RunInvalidateTodaysStoredPerformanceCheck
      parameters:
      - name: cancellationToken
        in: header
        required: true
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
            application/xml:
              schema:
                type: string
            text/xml:
              schema:
                type: string
            multipart/form-data:
              schema:
                type: string
      security:
      - Authorization: []
      summary: Rollups run invalidate todays stored performance check
      x-summary-source: derived
components:
  securitySchemes:
    Authorization:
      type: apiKey
      description: 'JWT Authorization header using the Session scheme. Example: "Authorization: Session {token}"'
      name: Authorization
      in: header
