openapi: 3.2.0
info:
  version: V1
  title: Orion Connect Trading/Contribution Codes API
  x-swagger-net-version: 8.4.12.001
servers:
- url: https://api.orionadvisor.com/api
tags:
- name: Trading/ContributionCodes
paths:
  /v1/Trading/ContributionCodes/Simple:
    get:
      tags:
      - Trading/ContributionCodes
      summary: Gets a simple list of contribution codes that the logged in user has access to
      operationId: ContributionCodes_GetContributionCodesSimple
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                items:
                  $ref: '#/components/schemas/OAS.DataModel.SimpleEntity'
                xml:
                  name: SimpleEntity
                  wrapped: true
                type: array
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/OAS.DataModel.SimpleEntity'
                xml:
                  name: SimpleEntity
                  wrapped: true
                type: array
            text/json:
              schema:
                items:
                  $ref: '#/components/schemas/OAS.DataModel.SimpleEntity'
                xml:
                  name: SimpleEntity
                  wrapped: true
                type: array
            application/xml:
              schema:
                items:
                  $ref: '#/components/schemas/OAS.DataModel.SimpleEntity'
                xml:
                  name: SimpleEntity
                  wrapped: true
                type: array
            text/xml:
              schema:
                items:
                  $ref: '#/components/schemas/OAS.DataModel.SimpleEntity'
                xml:
                  name: SimpleEntity
                  wrapped: true
                type: array
            multipart/form-data:
              schema:
                items:
                  $ref: '#/components/schemas/OAS.DataModel.SimpleEntity'
                xml:
                  name: SimpleEntity
                  wrapped: true
                type: array
      security:
      - Authorization: []
components:
  schemas:
    OAS.DataModel.SimpleEntity:
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
      xml:
        name: SimpleEntity
      type: object
  securitySchemes:
    Authorization:
      type: apiKey
      description: 'JWT Authorization header using the Session scheme. Example: "Authorization: Session {token}"'
      name: Authorization
      in: header
