openapi: 3.2.0
info:
  version: V1
  title: Orion Connect Monitor API
  x-swagger-net-version: 8.4.12.001
  description: Primary controller for public information.
servers:
- url: https://api.orionadvisor.com/api
tags:
- name: Monitor
  description: Primary controller for public information.
paths:
  /v1/Monitor:
    get:
      tags:
      - Monitor
      operationId: Monitor_Echo
      parameters:
      - name: echo
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: object
            application/json:
              schema:
                type: object
            text/json:
              schema:
                type: object
            multipart/form-data:
              schema:
                type: object
      security:
      - Authorization: []
      summary: Monitor echo
      x-summary-source: derived
components:
  securitySchemes:
    Authorization:
      type: apiKey
      description: 'JWT Authorization header using the Session scheme. Example: "Authorization: Session {token}"'
      name: Authorization
      in: header
